### ISSUE TITLE
Monitored resources should optionally have ownership definitions

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#22]
We should allow for having both high-level (project-wide) ownership, and also specifically at the resource-definition level.  This allows delegation of responsibilities across larger projects, including support (and specialized support).

Example (excerpt from [sprig-platform config definition](https://github.com/hackclub/slacker/blob/main/config/sprig.yaml)):

```
...
  - name: sprig-platform
    id: C04S1A8NT44
    owners: Graham, Fayd
    sla:
      responseTime: 24h
...
```
