### ISSUE TITLE
Monitored resources should support being split into subsections via pattern matching

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#23]
There may be cases where we would like to route specific questions to specific individuals with specific domain knowledge/expertise.  As such, resources defined in projects should support pattern matching of content to route specific work to specific people.  If no resource-scoped responsibilities are defined, the ownership hierarchy should be respected (defaulting to project-level owners).

Example (excerpt from [sprig-platform config definition](https://github.com/hackclub/slacker/blob/main/config/sprig.yaml)):

```
  - name: sprig-platform
    id: C04S1A8NT44
    owners:
        default:
            people: Fayd
        specialized-web-responsibility:
            people: Graham
            pattern: /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/
    sla:
      responseTime: 24h
```
*Note*: The above yaml is purely explanative and should be interpreted as pseudocode - do not take this specific example as exactly how we should implement this feature, find something that works 'good enough' and is clean.
