### ISSUE TITLE
Allow for project interdependencies

### ISSUE THREAD

**Issue by grymmy** [hackclub/slacker#28]
The current config looks like:

```
name: HQ Engineering
description: HQ Engineering stuff for Hack Club
maintainers: [faisal, graham, josias]
channels:
  - name: infra-alerts
    id: C05G25Y9M6V
    sla:
      responseTime: 1h
  - name: hq-engineering
    id: C05SVRTCDGV
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/slacker
    sla:
      responseTime: 1h
  - uri: https://github.com/hackclub/infra
    sla:
      responseTime: 1h
```
Consider tacking on the following, to also allow monitoring/responsibility for another project - thus we could have a hierarchy of sub-projects under one governing project:
```
projects:
  - uri: project://dns
```
One thing to consider is whether or not it's a good idea to allow any sort of cyclical dependencies, perhaps that should be validated and PRs rejected if that occurs...
